# Site settings
title: uGeek
description: "Podcast de Tecnología que hablo de Linux, Raspberry Pi, servidores y tecnología en general."
url: "https://angelbcn.github.io/ugeek/"
author:
  name: "Angel"
  email: "hello@jacoporabolini.com"
  url: "https://angelbcn.github.io/ugeek/"

# Build settings
baseurl: /ugeek/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/


# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

#Google Analitics
google_analytics: UA-96879567-1

# Podcast Feed Settings

title:          uGeek
email:          ugeekpodcast@gmail.com
description:    "Podcast de Tecnología en el que hablo de Linux, Raspberry Pi, servidores y tecnología en general."
subtitle:       "Podcast de Tecnología en el que hablo de Linux, Raspberry Pi, servidores y tecnología en general."
url:            angelbcn.github.io/ugeek/
lang:           Español
author:         Angel

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
